-
  version: '1.0.{build}'
  image: ubuntu
  environment:
    nodejs_version: "10"
  branches:
    only:
    - development
  cache:
    - '~/.config/yarn/global'
  init:
    - cmd: git config --global core.autocrlf true
  install:
    - sh: nvm install $nodejs_version
    # install modules
    - yarn
  test_script:
    # Output useful info for debugging.
    - node --version
    - yarn -v
    # run tests
    - yarn test:ci
  build_script:
    - yarn build:staging
  artifacts:
    - path: build\
      name: app
  deploy:
    - provider: Environment
      name: RPThreadTrackerV3-FrontEnd-Staging
  on_success:
    - ps: Invoke-RestMethod https://raw.githubusercontent.com/blackjackkent/appveyor-discord-webhook/master/send.ps1 -o send.ps1
    - ps: ./send.ps1 success $env:WEBHOOK_URL
  on_failure:
    - ps: Invoke-RestMethod https://raw.githubusercontent.com/blackjackkent/appveyor-discord-webhook/master/send.ps1 -o send.ps1
    - ps: ./send.ps1 failure $env:WEBHOOK_URL
-
  version: '1.0.{build}'
  image: ubuntu
  environment:
    nodejs_version: "10"
  branches:
    only:
    - production
  cache:
    - '~/.config/yarn/global'
  init:
    - cmd: git config --global core.autocrlf true
  install:
    - sh: nvm install $nodejs_version
    # install modules
    - yarn
  test_script:
    # Output useful info for debugging.
    - node --version
    - yarn -v
    # run tests
    - yarn test:ci
  build_script:
    - yarn build
  artifacts:
    - path: build\
      name: app
  deploy:
    - provider: Environment
      name: RPThreadTrackerV3-FrontEnd-Prod
  on_success:
    - ps: Invoke-RestMethod https://raw.githubusercontent.com/blackjackkent/appveyor-discord-webhook/master/send.ps1 -o send.ps1
    - ps: ./send.ps1 success $env:WEBHOOK_URL
  on_failure:
    - ps: Invoke-RestMethod https://raw.githubusercontent.com/blackjackkent/appveyor-discord-webhook/master/send.ps1 -o send.ps1
    - ps: ./send.ps1 failure $env:WEBHOOK_URL
